// SA5 catalog-builder. Merges data/_raw/<cat>.json + data/_raw/_ko/<cat>.json
// into the production data file src/app/products/data/thermal-catalog.ts.
// This file is the locked SA5 -> SA6 contract (D-6).
//
// Usage: node scripts/tglobal/build-catalog.mjs

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const RAW = join(ROOT, "data", "_raw");
const KO = join(RAW, "_ko");
const OUT = join(ROOT, "src", "app", "products", "data", "thermal-catalog.ts");

const CAT_KO = {
  "thermal-interface-materials": ["열전도 인터페이스 소재(TIM)", "Thermal Interface Materials"],
  "vapor-chamber": ["베이퍼 챔버", "Vapor Chambers"],
  "heat-pipes": ["히트파이프", "Heat Pipes"],
  "heat-sinks": ["방열판 · 히트싱크", "Heat Sinks"],
  "alsic": ["AlSiC 복합소재", "AlSiC"],
  "thermoelectric-cooling-chips": ["열전 냉각 칩(TEC)", "Thermoelectric Cooling Chips"],
  "flexible-absorbing-materials": ["플렉시블 흡수 소재", "Flexible Absorbing Materials"],
  "thermal-module": ["써멀 모듈", "Thermal Module"],
  "thermal-simulation": ["열 시뮬레이션", "Thermal Simulation"],
  "fan": ["팬", "Fans"],
};

const deriveModel = (title) => (title.match(/^[A-Za-z0-9][\w.\-\/]*/) || [title])[0].replace(/-$/, "");

const files = readdirSync(RAW).filter((f) => f.endsWith(".json") && f !== "urls.json");
const categories = [];

for (const base of files.sort()) {
  const slug = base.replace(/\.json$/, "");
  const raw = JSON.parse(readFileSync(join(RAW, base), "utf8"));
  const ko = existsSync(join(KO, base)) ? JSON.parse(readFileSync(join(KO, base), "utf8")) : {};
  const products = raw.map((p) => {
    const k = ko[p.slug] || {};
    const benefits = (k.benefits_ko || p.benefits || []).map((b) =>
      b.replace(/^⟦TODO⟧\s*/, "")
    );
    return {
      slug: p.slug,
      model: deriveModel(p.title),
      name: k.name_ko || p.title,
      nameEn: p.title,
      category: slug,
      categoryPath: p.categoryPath || [slug],
      benefits,
      description: (k.description_ko && k.description_ko.trim()) || k.description_en_clean || p.description || "",
      descriptionEn: k.description_en_clean || p.description || "",
      specs: p.specs || [],
      images: p.images || [],
      sourceUrl: p.url || "",
    };
  });
  const [nameKo, nameEn] = CAT_KO[slug] || [slug, slug];
  categories.push({ slug, nameKo, nameEn, products });
}

const total = categories.reduce((n, c) => n + c.products.length, 0);
const header = `// AUTO-GENERATED by scripts/tglobal/build-catalog.mjs — do not edit by hand.
// Source: tglobalcorp.com catalog migration (track: tglobal-catalog-migration).
// ${categories.length} categories, ${total} products. Specs kept verbatim (D-2).

export interface CatalogSpec {
  property: string;
  unit: string;
  value: string;
  testMethod: string;
}
export interface CatalogProduct {
  slug: string;
  model: string;
  name: string;
  nameEn: string;
  category: string;
  categoryPath: string[];
  benefits: string[];
  description: string;
  descriptionEn: string;
  specs: CatalogSpec[];
  images: string[];
  sourceUrl: string;
}
export interface CatalogCategory {
  slug: string;
  nameKo: string;
  nameEn: string;
  products: CatalogProduct[];
}

export const THERMAL_CATALOG: CatalogCategory[] = ${JSON.stringify(categories, null, 2)};

export const CATALOG_PRODUCT_COUNT = ${total};
`;

writeFileSync(OUT, header);
console.log(`[SA5] ${categories.length} categories, ${total} products -> ${OUT.replace(ROOT + "/", "")}`);
